=== Ivan-Gevalo/TerplanSymbology/Schemas/PlanProjectResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    XML-схема, описывающая структуру XML-файла, в котором приводятся сведения, содержащиеся в проекте планировки территории.
    Настоящая схема составлена в соответствии с приложением № 1 к приказу Министерства строительства и жилищно-коммунального хозяйства Российской Федерации от 11.12.2023 № 890/пр "Об установлении требований к форматам предоставления сведений, содержащихся в проекте планировки территории и проекте межевания территории".
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Response">
        <xs:annotation>
            <xs:documentation>Ответ на запрос сведений, содержащихся в проекте планировки территории</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PlanProject" type="PlanProjectResponseType">
                    <xs:annotation>
                        <xs:documentation>Информация о проекте планировки территории</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="Attachments" type="AttachmentType">
                    <xs:annotation>
                        <xs:documentation>Описание приложенных файлов</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PlanProjectResponseType">
        <xs:sequence>
            <xs:element name="NumberPlanProject">
                <xs:annotation>
                    <xs:documentation>Номер документа об утверждении проекта планировки территории</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="DatePlanProject" type="xs:date">
                <xs:annotation>
                    <xs:documentation>Дата документа об утверждении проекта планировки территории</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Other" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Иная информация о документе об утверждении проекта планировки территории</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="500"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ObjectNamePlanProject">
                <xs:annotation>
                    <xs:documentation>Наименование объекта капитального строительства</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="AmmendInfo" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Реквизиты документов, которыми внесены изменения в проект планировки территории (при наличии)</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="MiscInfo" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Иные сведения</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AttachmentType">
        <xs:sequence>
            <xs:element name="Attachment">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="IsunstructuredFогmаt" type="xs:boolean">
                            <xs:annotation>
                                <xs:documentation>Признак того, является или нет вложение неструктурированным</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="IsZipPacked" type="xs:boolean">
                            <xs:annotation>
                                <xs:documentation>Признак того, будет ли вложение помещено в zip-архив</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                        <xs:element name="ZipName" minOccurs="0">
                            <xs:annotation>
                                <xs:documentation>Имя архива</xs:documentation>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                    <xs:maxLength value="255"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="FileName">
                            <xs:annotation>
                                <xs:documentation>Имя файла</xs:documentation>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                    <xs:maxLength value="255"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="FileMimeType">
                            <xs:annotation>
                                <xs:documentation>Расширение файла</xs:documentation>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="(text|image|application)\/[a-zA-Z0-9\+-.]*"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Ivan-Gevalo/TerplanSymbology/Schemas/moc/PlanProjectResponse_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<Response xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PlanProjectResponse.xsd">
    <PlanProject>
        <NumberPlanProject>1</NumberPlanProject>
        <DatePlanProject>2025-01-01</DatePlanProject>
        <Other>Имются утвержденные изменения</Other>
        <ObjectNamePlanProject>Объект</ObjectNamePlanProject>
        <AmmendInfo>Постановление от 01.10.2025 № 63</AmmendInfo>
    </PlanProject>
    <Attachments>
        <Attachment>
            <IsUnstructuredFогmаt>false</IsUnstructuredFогmаt>
            <IsZipPacked>true</IsZipPacked>
            <ZipName>Архив</ZipName>
            <FileName>Чертеж планировки территории</FileName>
            <FileMimeType>image/pdf</FileMimeType>
        </Attachment>
        <Attachment>
            <IsUnstructuredFогmаt>false</IsUnstructuredFогmаt>
            <IsZipPacked>true</IsZipPacked>
            <ZipName>Архив</ZipName>
            <FileName>Положение о характеристиках планируемого развития территории</FileName>
            <FileMimeType>text/doc</FileMimeType>
        </Attachment>
    </Attachments>
</Response>
